stages:
  - upload
  - download
  - build
  - deploy

upload-artifact-job:
  stage: upload
  script:
    - sudo kubectl exec deployment/mlflow python train.py

download-job1:
  stage: download
  script:
    - python download.py

build-job:
  stage: build
  script:
    - sudo podman stop myapp
    - sudo podman rm myapp
    - sudo podman build -t myapp .
deploy-job:
  stage: deploy
  script:
      - sudo podman run -d -p 5000:5000 --name=myapp  myapp 

