- name: install pip
  shell: dnf install -y python-pip
- name: install dependency
  shell: pip install boto3
- name: download model.pkl
  shell: |
     cd myapp
     python download.py
- name: deploy myapp
  shell: |
     cd myapp
     podman build -t myapp .
     podman run -d -p 5000:5000 --name=myapp  myapp   
