- name: install registry
  shell: podman run -d -p 5000:5000 --restart=always --name registry registry:2
# - name: store registry ip 
#   shell: podman inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' registry
#   register: registry_ip
# - local_action: copy content={{ registry_ip }} dest=registry_ip.txt