- name: install minio configmap
  shell: |
    kubectl create -f minio-configmap.yaml
- name: install minio deployment and svc
  shell: |
    kubectl create -f minio/deployment.yaml
    kubectl create -f minio/service.yaml