apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-configmap
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_S3_ENDPOINT_URL: "http://s3:9000"
  