apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
  labels:
    app: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-s3-pods
  template:
    metadata:
      labels:
         app: aws-s3-pods
    spec:
      containers:
      - name: aws-s3-pod
        image: minio/minio:RELEASE.2021-06-14T01-29-23Z
        imagePullPolicy: Always
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: minio-configmap
                key: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: minio-configmap
                key: MINIO_SECRET_KEY
        ports:
          - containerPort: 9000
        command: ["minio","gateway","s3"]
             

         