version: '3.3'
services:
  s3:
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
    container_name: aws-s3
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    # command: 
    #   server /date
    command:
      minio gateway s3
    networks:
      - A
    # volumes:
    #   - ./s3:/date
networks:
    A:
        driver: bridge